disabled_rules: # rule identifiers to exclude from running
  #- trailing_whitespace
  - todo
  - line_length
  - void_return
  - closure_parameter_position
  - cyclomatic_complexity
  - large_tuple
included:
  - Shopfloor
excluded:
  #- Tests/SwiftLintFrameworkTests/Resources
opt_in_rules:
  #- empty_count
  #- file_header
  #- explicit_init
  #- closure_spacing
  #- overridden_super_call
  #- redundant_nil_coalescing
  #- private_outlet
  #- nimble_operator
  #- attributes
  #- operator_usage_whitespace
  #- closure_end_indentation
  #- first_where
  #- sorted_imports
  #- object_literal
  #- number_separator
  #- prohibited_super_call

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  FFSwiftExtensions
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} simaoseica\. All rights reserved\.
                    \/\/
line_length: 120
number_separator:
  minimum_length: 5
